### ISSUE TITLE
CI build fails with BindException

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-infinispan#1]
```
java.net.BindException: No available port to bind to in range [7800 .. 7850]
	at org.jgroups.util.Util.createServerSocket(Util.java:3048)
	at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:76)
	at org.jgroups.protocols.TCP.start(TCP.java:68)
	at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:966)
	at org.jgroups.JChannel.startStack(JChannel.java:890)
	at org.jgroups.JChannel._preConnect(JChannel.java:553)
	at org.jgroups.JChannel.connect(JChannel.java:288)
	at org.jgroups.JChannel.connect(JChannel.java:279)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:200)
```

**Comment by tsegismont** [comment]
Closed via 719508f295eaca23c7a8299790885384167743f6
