### ISSUE TITLE
InfinispanClusterManager.tryLock blocks the eventloop

### ISSUE THREAD

**Issue by ruslansennov** [vert-x3/vertx-infinispan#124]
Here is the observed stack trace. Refers to master and branch 4.x. 
Unfortunately I have no reproducer
```
io.vertx.core.VertxException: Thread blocked 
at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method) 
at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source) 
at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source) 
at app//org.jgroups.util.Credit.decrementIfEnoughCredits(Credit.java:65) 
at app//org.jgroups.protocols.UFC.handleDownMessage(UFC.java:119) 
at app//org.jgroups.protocols.FlowControl.down(FlowControl.java:323) 
at app//org.jgroups.protocols.FlowControl.sendCreditRequest(FlowControl.java:506) 
at app//org.jgroups.protocols.MFC.handleDownMessage(MFC.java:126) 
at app//org.jgroups.protocols.FlowControl.down(FlowControl.java:323) 
at app//org.jgroups.protocols.FRAG3.down(FRAG3.java:139) 
at app//org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:927) 
at app//org.jgroups.JChannel.down(JChannel.java:645) 
at app//org.jgroups.JChannel.send(JChannel.java:484) 
at app//org.infinispan.remoting.transport.jgroups.JGroupsTransport.send(JGroupsTransport.java:1161) 
at app//org.infinispan.remoting.transport.jgroups.JGroupsTransport.sendCommandToAll(JGroupsTransport.java:1275) 
at app//org.infinispan.remoting.transport.jgroups.JGroupsTransport.invokeCommandOnAll(JGroupsTransport.java:1040) 
at app//org.infinispan.remoting.rpc.RpcManagerImpl.invokeCommandOnAll(RpcManagerImpl.java:244) 
at app//org.infinispan.interceptors.distribution.BaseDistributionInterceptor.primaryReturnHandler(BaseDistributionInterceptor.java:285) 
at app//org.infinispan.interceptors.distribution.BaseDistributionInterceptor$$Lambda$716/0x0000000801054f60.apply(Unknown Source) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextThenApply(BaseAsyncInterceptor.java:86) 
at app//org.infinispan.interceptors.distribution.BaseDistributionInterceptor.handleNonTxWriteCommand(BaseDistributionInterceptor.java:244) 
at app//org.infinispan.interceptors.distribution.NonTxDistributionInterceptor.visitReadWriteKeyCommand(NonTxDistributionInterceptor.java:153) 
at app//org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:91) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:59) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.asyncInvokeNext(BaseAsyncInterceptor.java:232) 
at app//org.infinispan.interceptors.impl.EntryWrappingInterceptor.setSkipRemoteGetsAndInvokeNextForDataCommand(EntryWrappingInterceptor.java:784) 
at app//org.infinispan.interceptors.impl.EntryWrappingInterceptor.visitReadWriteKeyCommand(EntryWrappingInterceptor.java:551) 
at app//org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:91) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndFinally(BaseAsyncInterceptor.java:155) 
at app//org.infinispan.interceptors.locking.AbstractLockingInterceptor.lambda$nonTxLockAndInvokeNext$3(AbstractLockingInterceptor.java:318) 
at app//org.infinispan.interceptors.locking.AbstractLockingInterceptor$$Lambda$1115/0x000000080129b798.apply(Unknown Source) 
at app//org.infinispan.interceptors.SyncInvocationStage.andHandle(SyncInvocationStage.java:69) 
at app//org.infinispan.interceptors.locking.AbstractLockingInterceptor.nonTxLockAndInvokeNext(AbstractLockingInterceptor.java:313) 
at app//org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitNonTxDataWriteCommand(AbstractLockingInterceptor.java:138) 
at app//org.infinispan.interceptors.locking.NonTransactionalLockingInterceptor.visitDataWriteCommand(NonTransactionalLockingInterceptor.java:41) 
at app//org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitReadWriteKeyCommand(AbstractLockingInterceptor.java:202) 
at app//org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:91) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:59) 
at app//org.infinispan.partitionhandling.impl.PartitionHandlingInterceptor.handleSingleWrite(PartitionHandlingInterceptor.java:92) 
at app//org.infinispan.partitionhandling.impl.PartitionHandlingInterceptor.visitReadWriteKeyCommand(PartitionHandlingInterceptor.java:85) 
at app//org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:91) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndHandle(BaseAsyncInterceptor.java:188) 
at app//org.infinispan.statetransfer.StateTransferInterceptor.handleNonTxWriteCommand(StateTransferInterceptor.java:312) 
at app//org.infinispan.statetransfer.StateTransferInterceptor.handleWriteCommand(StateTransferInterceptor.java:256) 
at app//org.infinispan.statetransfer.StateTransferInterceptor.visitReadWriteKeyCommand(StateTransferInterceptor.java:167) 
at app//org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:91) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextThenApply(BaseAsyncInterceptor.java:79) 
at app//org.infinispan.interceptors.impl.CacheMgmtInterceptor.updateStatisticsReadWrite(CacheMgmtInterceptor.java:384) 
at app//org.infinispan.interceptors.impl.CacheMgmtInterceptor.visitReadWriteKeyCommand(CacheMgmtInterceptor.java:419) 
at app//org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:91) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:59) 
at app//org.infinispan.interceptors.DDAsyncInterceptor.handleDefault(DDAsyncInterceptor.java:55) 
at app//org.infinispan.interceptors.DDAsyncInterceptor.visitReadWriteKeyCommand(DDAsyncInterceptor.java:207) 
at app//org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:91) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndExceptionally(BaseAsyncInterceptor.java:128) 
at app//org.infinispan.interceptors.impl.InvocationContextInterceptor.visitCommand(InvocationContextInterceptor.java:89) 
at app//org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:61) 
at app//org.infinispan.interceptors.DDAsyncInterceptor.handleDefault(DDAsyncInterceptor.java:55) 
at app//org.infinispan.interceptors.DDAsyncInterceptor.visitReadWriteKeyCommand(DDAsyncInterceptor.java:207) 
at app//org.infinispan.commands.functional.ReadWriteKeyCommand.acceptVisitor(ReadWriteKeyCommand.java:91) 
at app//org.infinispan.interceptors.DDAsyncInterceptor.visitCommand(DDAsyncInterceptor.java:51) 
at app//org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invokeAsync(AsyncInterceptorChainImpl.java:220) 
at app//org.infinispan.functional.impl.AbstractFunctionalMap.invokeAsync(AbstractFunctionalMap.java:131) 
at app//org.infinispan.functional.impl.ReadWriteMapImpl.eval(ReadWriteMapImpl.java:56) 
at app//org.infinispan.lock.impl.lock.ClusteredLockImpl.tryLock(ClusteredLockImpl.java:435) 
at app//org.infinispan.lock.impl.lock.ClusteredLockImpl.tryLock(ClusteredLockImpl.java:422) 
at app//io.vertx.ext.cluster.infinispan.InfinispanClusterManager.tryLock(InfinispanClusterManager.java:161) 
at app//io.vertx.ext.cluster.infinispan.InfinispanClusterManager.lambda$getLockWithTimeout$2(InfinispanClusterManager.java:153) 
at app//io.vertx.ext.cluster.infinispan.InfinispanClusterManager$$Lambda$1433/0x00000008014634a0.handle(Unknown Source) 
at app//io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) 
at app//io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) 
at app//io.vertx.core.impl.future.FutureBase$$Lambda$891/0x0000000801106fd8.run(Unknown Source) 
at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) 
at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) 
at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) 
at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) 
at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) 
at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
at java.base@17.0.5/java.lang.Thread.run(Unknown Source)
```

**Comment by tsegismont** [comment]
Fixed in 4bdb4c4
