### ISSUE TITLE
Nodes is waiting for state for ever

### ISSUE THREAD

**Issue by bdarwin** [vert-x3/vertx-infinispan#32]
With 3.4.2-SNAPSHOT when I use TCPPING as discovery then cluster is not going beyond 3 nodes.
From 4th node I see below exception and node never starts.

```
2017-04-15 01:59:05.049 vertx-blocked-thread-checker WARN  impl.BlockedThreadChecker -  Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 179678 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.infinispan.statetransfer.StateTransferManagerImpl.waitForInitialStateTransferToComplete(StateTransferManagerImpl.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.infinispan.commons.util.SecurityActions.lambda$invokeAccessibly$0(SecurityActions.java:91)
	at org.infinispan.commons.util.SecurityActions$$Lambda$27/21723014.run(Unknown Source)
	at org.infinispan.commons.util.SecurityActions.doPrivileged(SecurityActions.java:83)
	at org.infinispan.commons.util.SecurityActions.invokeAccessibly(SecurityActions.java:88)
	at org.infinispan.commons.util.ReflectionUtil.invokeAccessibly(ReflectionUtil.java:165)
	at org.infinispan.factories.AbstractComponentRegistry$PrioritizedMethod.invoke(AbstractComponentRegistry.java:869)
	at org.infinispan.factories.AbstractComponentRegistry.invokeStartMethods(AbstractComponentRegistry.java:635)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:624)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:549)
	at org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.java:231)
	at org.infinispan.cache.impl.CacheImpl.start(CacheImpl.java:803)
	at org.infinispan.cache.impl.AbstractDelegatingCache.start(AbstractDelegatingCache.java:411)
	at org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultCacheManager.java:652)
	at org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheManager.java:592)
	at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:456)
	at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:446)
	at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:431)
	at io.vertx.ext.cluster.infinispan.InfinispanClusterManager.getSyncMap(InfinispanClusterManager.java:149)
	at io.vertx.core.impl.HAManager.<init>(HAManager.java:144)
	at io.vertx.core.impl.VertxImpl.lambda$new$0(VertxImpl.java:190)
	at io.vertx.core.impl.VertxImpl$$Lambda$175/1984577117.handle(Unknown Source)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:188)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:287)
	at io.vertx.core.impl.ContextImpl$$Lambda$179/685766973.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl$$Lambda$180/705548221.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

```

Here is the channel config.
Passing these as system props  

bind_addr=machine ip address
bind_port=4501
port_range=50

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:org:jgroups"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
    <TCP_NIO2 bind_port="${jgroups.tcpnio}"
              recv_buf_size="${tcp.recv_buf_size:130k}"
              send_buf_size="${tcp.send_buf_size:130k}"
              max_bundle_size="64K"
              sock_conn_timeout="300"
              thread_pool.min_threads="0"
              thread_pool.max_threads="20"
              thread_pool.keep_alive_time="30000"
    />
    <TCPPING async_discovery="true"/>
    <MERGE3 min_interval="10000"
            max_interval="30000"/>
    <FD_SOCK/>
    <FD_ALL timeout="30000"/>
    <VERIFY_SUSPECT timeout="1500"/>
    <BARRIER/>
    <pbcast.NAKACK2 use_mcast_xmit="false"
                    discard_delivered_msgs="true"/>
    <UNICAST3/>
    <pbcast.STABLE desired_avg_gossip="50000"
                   max_bytes="4M"/>
    <pbcast.GMS print_local_addr="true" join_timeout="2000"
                view_bundling="true"/>
    <MFC max_credits="2M"
         min_threshold="0.4"/>
    <FRAG2 frag_size="60K"/>
    <!--RSVP resend_interval="2000" timeout="10000"/-->
    <pbcast.STATE_TRANSFER  />
</config> 
```

However when I add <MPING/> tag after TCPPING everything works fine. Though I haven't tested across different machines at least I can start 11 nodes without any issues on the same machine. 

What am I missing here? Why 4th nodes fails to start without MPING?

**Comment by tsegismont** [comment]
@bdarwin I'm not sure TCPPING works without the `initial_hosts` attribute. 

See [Using TCP and TCPPING](http://www.jgroups.org/manual/index.html#TCPPING)

> The concept behind TCPPING is that some selected cluster members assume the role of well-known hosts from which the initial membership information can be retrieved.

Besides, your protocol stack looks much different than the Infinispan standard. I'd start from the [default-jgroups-tcp.xml](https://github.com/infinispan/infinispan/blob/9.0.0.Final/core/src/main/resources/default-configs/default-jgroups-tcp.xml) and replace `MPING` by `TCPPING`.

**Comment by tsegismont** [comment]
Closing, needs more info
