### ISSUE TITLE
Cache '__vertx.subs' removed multiple times cause the vertx.close() hangs forever

### ISSUE THREAD

**Issue by castx1981** [vert-x3/vertx-infinispan#57]
Here is the unit test I wrote to create two vertx nodes, one is deployed an eventbus verticle, another one is deployed an http verticle, they communicate via eventbus.

```
  private static Vertx[] vertx = new Vertx[3];
  private static WebClient webClient;

  @BeforeClass
  public static void setUpClass(TestContext context) {
    final VertxOptions vertxOptions = new VertxOptions()
      .setClustered(true)
      .setClusterManager(new InfinispanClusterManager());

    Async async1 = context.async();
    TestUtils.joinClusterAndDeployVerticle(vertxOptions, new PlusEventBusVerticle(), ar -> {
      if (ar.succeeded()) {
        vertx[0] = ar.result();
        async1.complete();
      } else {
        context.fail(ar.cause());
      }
    });
    async1.awaitSuccess();

    Async async2 = context.async();
    TestUtils.joinClusterAndDeployVerticle(vertxOptions, new PlusHttpVerticle(), ar -> {
      if (ar.succeeded()) {
        vertx[1] = ar.result();
        async2.complete();
      } else {
        context.fail(ar.cause());
      }
    });
    async2.awaitSuccess();

    vertx[2] = Vertx.vertx();
    webClient = WebClient.create(vertx[2], new WebClientOptions()
      .setDefaultHost("localhost")
      .setDefaultPort(PlusHttpVerticle.PORT));

  }

  @AfterClass
  public static void tearDownClass(TestContext context) {
    vertx[2].close(context.asyncAssertSuccess(v1 ->
      vertx[1].close(context.asyncAssertSuccess(v2 ->
        vertx[0].close(context.asyncAssertSuccess())))
    ));
  }

  @Test
  public void testOperation(TestContext context) {
    webClient.get("/plus")
      .addQueryParam("a", "4")
      .addQueryParam("b", "5")
      .send(context.asyncAssertSuccess(response ->
        context.assertEquals("9", response.bodyAsString())
      ));
```

It works fine until the tearDownClass to close all the vertx instances, here is the log:
```
    10:36:18.852 [vert.x-worker-thread-0] INFO  org.infinispan.remoting.transport.jgroups.JGroupsTransport - ISPN000078: Starting JGroups channel ISPN
    10:36:24.072 [vert.x-worker-thread-0] INFO  org.infinispan.CLUSTER - ISPN000094: Received new cluster view for channel ISPN: [Luans-iMac-18012|0] (1) [Luans-iMac-18012]
    10:36:24.082 [vert.x-worker-thread-0] INFO  org.infinispan.remoting.transport.jgroups.JGroupsTransport - ISPN000079: Channel ISPN local address is Luans-iMac-18012, physical addresses are [127.0.0.1:7800]
    10:36:24.086 [vert.x-worker-thread-0] INFO  org.infinispan.factories.GlobalComponentRegistry - ISPN000128: Infinispan version: Infinispan 'Bastille' 9.1.3.Final
    10:36:26.066 [vert.x-worker-thread-3] INFO  org.infinispan.remoting.transport.jgroups.JGroupsTransport - ISPN000080: Disconnecting JGroups channel ISPN
    10:36:26.091 [vert.x-eventloop-thread-1] ERROR io.vertx.core.eventbus.impl.clustered.ClusteredEventBus - Failed to remove sub
    org.infinispan.IllegalLifecycleStateException: ISPN000323: Cache '__vertx.subs' is in 'TERMINATED' state and so it does not accept new invocations. Either restart it or recreate the cache container.
        at org.infinispan.interceptors.impl.InvocationContextInterceptor.ignoreCommand(InvocationContextInterceptor.java:104)
        at org.infinispan.interceptors.impl.InvocationContextInterceptor.visitCommand(InvocationContextInterceptor.java:93)
        at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:60)
        at org.infinispan.interceptors.DDAsyncInterceptor.handleDefault(DDAsyncInterceptor.java:54)
        at org.infinispan.interceptors.DDAsyncInterceptor.visitRemoveCommand(DDAsyncInterceptor.java:65)
        at org.infinispan.commands.write.RemoveCommand.acceptVisitor(RemoveCommand.java:63)
        at org.infinispan.interceptors.DDAsyncInterceptor.visitCommand(DDAsyncInterceptor.java:50)
        at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:248)
        at org.infinispan.cache.impl.CacheImpl.executeCommandAndCommitIfNeeded(CacheImpl.java:1661)
        at org.infinispan.cache.impl.CacheImpl.remove(CacheImpl.java:446)
        at org.infinispan.cache.impl.CacheImpl.remove(CacheImpl.java:440)
        at org.infinispan.cache.impl.AbstractDelegatingCache.remove(AbstractDelegatingCache.java:298)
        at org.infinispan.cache.impl.EncoderCache.remove(EncoderCache.java:585)
        at io.vertx.ext.cluster.infinispan.impl.InfinispanAsyncMultiMap.lambda$remove$8(InfinispanAsyncMultiMap.java:167)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
If I remove the last line `vertx[0].close(...)` from tearDownClass, it works fine. It seems both nodes are trying to remove __vertx.subs cache, but after it was removed, the subsequent remove are not allowed on infinispan and cause hang

**Comment by tsegismont** [comment]
You can ignore the exception stack trace. It happens because when node[2] is closed, one of the other nodes try to modify the eventbus subscription store (`__vertx.subs`), but this node is shutdown as well very quickly.

The exception should not block the shutdown process though, nor fail your test. Can you provide an executable reproducer? Thank you

**Comment by castx1981** [comment]
Sure, I will attach the code in a while.
