### ISSUE TITLE
NullPointerException when running in fat jar

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-infinispan#87]
When packaging the Vert.x app as a fat jar (e.g with Maven Shade Plugin), the cluster fails to start, throwing a `NullPointerException` such as:

```
java.lang.NullPointerException
        at org.infinispan.counter.EmbeddedCounterManagerFactory.asCounterManager(EmbeddedCounterManagerFactory.java:28)
        at io.vertx.ext.cluster.infinispan.InfinispanClusterManager.lambda$join$8(InfinispanClusterManager.java:255)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

This happens because Infinispan uses some service files that need to be merged.

This applies to `4.0.0.CR1` and `3.9.4`

**Comment by tsegismont** [comment]
In 03781f7 , the documentation for Vert.x 4 has been updated

In Vert.x 3, the files that you need to merge are almost the same:

xml
```
<resource>META-INF/services/org.infinispan.configuration.parsing.ConfigurationParser</resource>
<resource>META-INF/services/org.infinispan.factories.components.ModuleMetadataFileFinder</resource>
<resource>META-INF/services/org.infinispan.lifecycle.ModuleLifecycle</resource>
```

The cluster though still fails to start:

```
SEVERE: Failed to join cluster
org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheException: Failure while registering mbeans
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:711)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:676)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:350)
        at io.vertx.ext.cluster.infinispan.InfinispanClusterManager.lambda$join$8(InfinispanClusterManager.java:242)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.infinispan.commons.CacheException: Failure while registering mbeans
        at org.infinispan.jmx.ComponentsJmxRegistration.registerMBeans(ComponentsJmxRegistration.java:60)
        at org.infinispan.jmx.CacheManagerJmxRegistration.registerMBean(CacheManagerJmxRegistration.java:123)
        at org.infinispan.counter.impl.CounterModuleLifecycle.registerCounterManager(CounterModuleLifecycle.java:100)
        at org.infinispan.counter.impl.CounterModuleLifecycle.cacheManagerStarting(CounterModuleLifecycle.java:146)
        at org.infinispan.factories.GlobalComponentRegistry.preStart(GlobalComponentRegistry.java:253)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:322)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:708)
        ... 8 more
Caused by: java.lang.NullPointerException
        at org.infinispan.jmx.ComponentsJmxRegistration.getObjectName(ComponentsJmxRegistration.java:81)
        at org.infinispan.jmx.ComponentsJmxRegistration.registerMBeans(ComponentsJmxRegistration.java:57)
        ... 14 more
```

Does that ring a bell @karesti ?

**Comment by karesti** [comment]
@pruivo here ?

**Comment by pruivo** [comment]
what's the Infinispan version?

**Comment by tsegismont** [comment]
@pruivo `9.4.10.Final` is the default with Vert.x 3. But I get the same problem with Vert.x 3 and  ISPN `9.4.20.Final`

**Comment by tsegismont** [comment]
@pruivo Would you like to create a reproducer?

**Comment by pruivo** [comment]
can you confirm the following file is in the fat jar: `infinispan-clustered-counter-component-metadata.dat`?
And the class `org.infinispan.counter.impl.CounterMetadataFileFinder` should be in file `org.infinispan.factories.components.ModuleMetadataFileFinder` as well.

**Comment by tsegismont** [comment]
Le jeu. 19 nov. 2020 à 11:51, Pedro Ruivo <notifications@github.com> a
écrit :

> can you confirm the following file is in the fat jar:
> infinispan-clustered-counter-component-metadata.dat?
>
Yes it is.


> And the class org.infinispan.counter.impl.CounterMetadataFileFinder
> should be in file
> org.infinispan.factories.components.ModuleMetadataFileFinder as well.
>

It isn't, even though I have configured the Maven Shade Plugin to merge the
ModuleMetadataFileFinder service files.
Thanks for pointing me in this direction, I'll investigate more and keep
you informed.

**Comment by tsegismont** [comment]
@pruivo @karesti I replaced the `AppendingResourceTransformer` with:

```
<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
```

And now it works with Vert.x 3 too. I'm not sure what's wrong, `AppendingResourceTransfromer` had worked for me before...

Anyway, thank you for you help! Much appreciated

**Comment by tsegismont** [comment]
Doc for 3.9 (dca1323810418e10563003c2c97f788b567ad1ec) and 4.x is updated. Closing.
